---

- assert:
    that:
      - PACKAGES_PROXY != ''
  tags: ['check_vars']

- name: Download NGINX Packages
  become: yes
  become_user: root
  yum: name={{ item }} state=present
  with_items: "{{ PACKAGES_PROXY }}"

- name: Install NGINX
  become: yes
  become_user: root
  yum: name={{ item }} state=present
  with_items:
    - nginx

- name: "chkconfig / nginx"
  become: yes
  become_user: root
  shell: "{{ item }}"
  with_items:
    - "chkconfig nginx on"
  notify:
    - restart nginx
