---

- name: tomcat6 / install
  become: yes
  become_user: root
  yum: name={{ item }} state=present
  with_items:
    - tomcat6

- name: "tomcat6 / chkconfig"
  become: yes
  become_user: root
  shell: "{{ item }}"
  with_items:
    - "chkconfig tomcat6 on"
  notify:
    - restart tomcat6
